spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:boxfitdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:boxfit}
    password: ${DB_PASSWORD:boxfit}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true


app:
  jwt:
    secret: "changeit-changeit-changeit-changeit-123456"
    expiration-ms: 3600000